version: '2'

services:  # containers. same as docker run
  
  ci-container: # a friendly name. this is also DNS name inside network
    container_name: ci-container
    build: .
    ports: 
      - "8085:5000"
    volumes: # Optional, same as -v in docker run
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always


volumes:
  /var/run/docker.sock: